src/objects/Buyer__c.object
<CustomObject>
    <description>Buyer is an organisation that is able to access the catalog.
It is possible to set up a list of products with negotiated prices for each Buyer
Buyers authenticate by sending username/password via OCI</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>sent in ``password&apos;&apos; parameter via OCI when accessing the OCI_Entry page</description>
        <inlineHelpText>Sent in ``password&apos;&apos; parameter via OCI when accessing the OCI_Entry page
This has to be configured in the Buyer&apos;s SAP system.</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>sent in ``username&apos;&apos; parameter via OCI when accessing the OCI_Entry page</description>
        <inlineHelpText>Sent in ``username&apos;&apos; parameter via OCI when accessing the OCI_Entry page
This has to be configured in the Buyer&apos;s SAP system</inlineHelpText>
        <label>User Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Buyer</label>
    <nameField>
        <label>Buyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SicCategory__c.object
<CustomObject>
    <description>category of a product</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SicProduct__c.object
<CustomObject>
    <description>A Product in the Product Catalog
Note: don&apos;t make any field required, only set it required on page layouts
This will ensure that the customization works</description>
    <fields>
        <fullName>Currency__c</fullName>
        <description>Item currency.
Must be maintained as ISO code in the SRM server.</description>
        <inlineHelpText>Item currency.
Must be maintained as ISO code in the SRM server.</inlineHelpText>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the item</description>
        <inlineHelpText>Description of the item</inlineHelpText>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Lead_Time_Display__c</fullName>
        <description>Lead Time in text format</description>
        <formula>&apos;in &apos; +  TEXT(Lead_Time__c) + &apos; days&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Lead Time in text format</inlineHelpText>
        <label>Usually Ships</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <description>Delivery time of the item in days</description>
        <inlineHelpText>Delivery time of the item in days</inlineHelpText>
        <label>Lead Time</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <description>Long Description
Description of a configuration, for example.</description>
        <inlineHelpText>Long Description
Description of a configuration, for example.</inlineHelpText>
        <label>Long Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Product_Number__c</fullName>
        <description>Manufacturer Product Number
This information is sent via OCI</description>
        <inlineHelpText>Manufacturer Product Number</inlineHelpText>
        <label>Manufacturer Product Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Display__c</fullName>
        <description>Price displayed as &apos;10 CAD per 1 EA&apos;</description>
        <formula>TEXT(Price__c) +  &apos; &apos; + TEXT(Currency__c) + IF(Unit_Text__c &lt;&gt; &apos;Each&apos;, &apos; per &apos;, &apos;&apos;) +   IF(Price_Unit__c &gt; 1, TEXT(Price_Unit__c), &apos;&apos;)   + &apos; &apos; +  Unit_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>price displayed with currency and price unit</inlineHelpText>
        <label>Price Per Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Unit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Price unit of the item</description>
        <inlineHelpText>Price unit of the item</inlineHelpText>
        <label>Price Unit</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of an item per price unit</description>
        <inlineHelpText>Price of an item per price unit</inlineHelpText>
        <label>Price</label>
        <precision>14</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNSPSC_code__c</fullName>
        <description>UNSPSC Commodity Code, use this in OCI</description>
        <formula>UNSPSC__r.Commodity_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UNSPSC Commodity Code</inlineHelpText>
        <label>UNSPSC code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_ISO__c</fullName>
        <description>Unit ISO code</description>
        <formula>Unit__r.ISO__c</formula>
        <inlineHelpText>Unit ISO code, use this for OCI</inlineHelpText>
        <label>UnitISO</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Text__c</fullName>
        <description>Unit described with Text</description>
        <formula>Unit__r.Text__c</formula>
        <inlineHelpText>Unit</inlineHelpText>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OCIController.cls
public with sharing class OCIController {

    public String FUNCTION {get; set; }
    public String HOOK_URL {get; set; }
    public String OCI_VERSION {get; set; }
    public String OPI_VERSION {get; set; }
    public String http_content_charset {get; set;}
    public String returntarget {get; set;}
    public String PRODUCTID {get; set; }
    public String QTY {get; set; }
    public String SEARCHSTRING {get; set; }
    private String username;
    private String password;
    private ID buyerID;
    private Dao dao;
    private Map<ID, OCIProduct> FoundAllProducts;
    private Map<ID, OCIProduct> FoundApprovedProducts;
    private Map<ID, OCIProduct> SelectedProducts;
    private Map<ID, SicCategory__c> categories;

    public OCIController() {
        System.debug(ApexPages.currentPage().getParameters());
        this.FUNCTION = ApexPages.currentPage().getParameters().get('FUNCTION');
        this.HOOK_URL = ApexPages.currentPage().getParameters().get('HOOK_URL');
        this.OCI_VERSION = ApexPages.currentPage().getParameters().get('OCI_VERSION');
        this.OPI_VERSION = ApexPages.currentPage().getParameters().get('OPI_VERSION');
        this.http_content_charset = ApexPages.currentPage().getParameters().get('http_content_charset');
        this.returntarget = ApexPages.currentPage().getParameters().get('returntarget');
        this.PRODUCTID = ApexPages.currentPage().getParameters().get('PRODUCTID');
        this.QTY = ApexPages.currentPage().getParameters().get('QUANTITY');
        this.SEARCHSTRING = ApexPages.currentPage().getParameters().get('SEARCHSTRING');
        this.currentCategoryID = 'all'; //needs to be inititalized
        username = ApexPages.currentPage().getParameters().get('username');
        password = ApexPages.currentPage().getParameters().get('password');
        try {
            Buyer__c buyer = [select id from Buyer__c where User_Name__c = :username and Password__c =: password];
            buyerID = buyer.id;
        }
        catch (System.QueryException qe) {
            buyerID = null;
        }
         
        this.dao = DaoFactory.getDao();
        // initialize private variables here!
        this.categories = new Map<ID, SicCategory__c>([select id, name from SicCategory__c]);
        this.FoundAllProducts = dao.fetchAllToMap(buyerID);
        this.FoundApprovedProducts = findApprovedProducts(FoundAllProducts);
        System.debug(this.FoundAllProducts);
        this.SelectedProducts = new Map<ID, OCIProduct>();
        this.filterApprovedOnly = false;
        this.currentProductID = null;
    }

    // navigation methods
    //*******************
    public PageReference displayCheckout() {
        PageReference pref = Page.OCI_Checkout;
        return pref;
    }

    public PageReference displayCatalog() {
                PageReference pref = Page.OCI_Catalog;
                return pref;
    }
    
    public PageReference displayDetail() {
        PageReference pref = Page.OCI_Detail;
        this.PRODUCTID = currentProductId;
        return pref;
    }
    // properties
    //***********
    // search for this text
    public String searchFor {
        get {
            return searchFor;
        }
        set {
            searchFor = value.trim();
        }
    }
    
    // list of Products found    
    public List<OCIProduct> getFoundProducts(){
        if(this.filterApprovedOnly) {
            return this.FoundApprovedProducts.values();
        }   
        else
            return this.FoundAllProducts.values();
    }
    public String getNumberOfProductsFound() {
        if(this.filterApprovedOnly)
            return this.FoundApprovedProducts.size().format();
        else
            return this.FoundAllProducts.size().format();
    }
    // list of Products selected into the shopping basket
    public List<OCIProduct> getSelectedProducts() {
        return this.SelectedProducts.values();
    }
    public void setSelectedProducts(List<OCIProduct> selection) {
        for(OCIProduct op : selection)
                this.SelectedProducts.put(op.getID(), op);
    }

    public String currentCategoryID {get; set;}
    public List<SicCategory__c> getCategories() {
        return categories.values();
    }
    public String getCurrentcategoryName() {
        if(currentCategoryID.trim().equals('all'))
            return 'All';
        else
            return categories.get(currentCategoryID).name;
    }
    public Attachment[] getAttachments() {
        return [select id, name, description from Attachment where parentID = :PRODUCTID];
    }
    
    public OCIProduct getDetailProduct() {
        return dao.fetchProductbyID(PRODUCTID, buyerID);
    }
    
    public boolean getIsBuyer() {
        return ( buyerID != null);
    }
    public boolean filterApprovedOnly {get; set;}
    
    // Action methods
    // **************
    // current product ID
    // action methods are invoked from command links 
    // that first set this property to provide context
    public ID currentProductID {
        get; 
        set {
            currentProductID = value;
            System.debug(currentProductID);
        }
    }

    public PageReference addCurrentProductToSelected() {
        OCIProduct product = FoundAllProducts.get(currentProductID);
        if (product == null)
                product = dao.fetchProductByID(currentProductID, buyerID);
                //[select id, name, Description__c, Long_Description__c, Lead_Time__c, Lead_Time_Display__c, Price__c, Price_Unit__c, Price_Display__c, Unit_Text__c, Unit_ISO__c, Currency__c, Manufacturer_Product_Number__c, UNSPSC_code__c from SicProduct__c WHERE id = :currentProductID];
        if (SelectedProducts == null) SelectedProducts = new Map<ID, OCIProduct>();
        SelectedProducts.put(currentProductID, product);
        return null;
    }
    public PageReference addToCartAndDisplayCatalog() {
        addCurrentPRoductToSelected();
        return displayCatalog();
    }
    public PageReference removeCurrentProductFromSelected() {
        this.SelectedProducts.remove(currentProductID);
        return null;
    }
        
    // search action
    public PageReference SearchProducts() {
        if(searchFor == null) searchFor = '';
        FoundAllProducts = dao.searchProductsByKeyword(SearchFor, currentCategoryID, buyerID);
        this.FoundApprovedProducts = findApprovedProducts(FoundAllProducts);
        return null;
    }
    
    // init: capture parameters from OCI call and route request
    public PageReference init() {
        if (FUNCTION == 'DETAIL') {
            Pagereference pref = Page.OCI_Detail;
            pref.getParameters().put('username', username);
            pref.getParameters().put('password', password);
            pref.getParameters().put('PRODUCTID', PRODUCTID);
            pref.setRedirect(true);
            return pref;
        }
        else if (FUNCTION == 'VALIDATE') {
            OCIProduct product = dao.fetchProductbyID(PRODUCTID, buyerID);
            product.setQuantity(QTY.trim());
            SelectedProducts = new Map<ID, OCIProduct>();
            SelectedProducts.put(product.getID(), product);
            return null;
        }
        else if (FUNCTION == 'BACKGROUND_SEARCH') {
            SelectedProducts = dao.searchProductsByKeyword('*' + SEARCHSTRING + '*', 'all', buyerID);
            return null; // background search has to use the same URL
        }
        else { //default: show Product Catalog
            PageReference pref = Page.OCI_Catalog;
            pref.getParameters().put('username', username);
            pref.getParameters().put('password', password);
            pref.getParameters().put('HOOK_URL', HOOK_URL);
            pref.getParameters().put('returntarget', returntarget);
            pref.setRedirect(true);
            return pref;
        }
    }
    
    private Map<ID, OCIProduct> findApprovedProducts(Map<ID, OCIProduct> all) {
        System.debug(all);
        Map<ID, OCIProduct> approved = all.clone();
        for(OCIProduct p : all.values()) {
            if(!p.getApproved()) {
                approved.remove(p.getID());
            }
        }
        return approved;
    }
    
}