src/objects/Buyer__c.object
<CustomObject>
    <description>Buyer is an organisation that is able to access the catalog.
It is possible to set up a list of products with negotiated prices for each Buyer
Buyers authenticate by sending username/password via OCI</description>
    <label>Buyer</label>
    <nameField>
        <label>Buyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negotiated_Product__c.object
<CustomObject>
    <description>Products that a Buyer has approved from the entire product list.
Products have a negotiated price.</description>
    <fields>
        <fullName>Buyer__c</fullName>
        <label>Buyer</label>
        <referenceTo>Buyer__c</referenceTo>
        <relationshipLabel>Negotiated Products</relationshipLabel>
        <relationshipName>Negotiated_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Negotiated_Price__c</fullName>
        <label>Negotiated Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Display__c</fullName>
        <formula>TEXT(Negotiated_Price__c) + &apos; &apos; + TEXT(Product__r.Currency__c) + IF(Product__r.Unit_Text__c &lt;&gt; &apos;Each&apos;, &apos; per &apos;, &apos;&apos;) + IF(Product__r.Price_Unit__c &gt; 1, TEXT(Product__r.Price_Unit__c), &apos;&apos;) + &apos; &apos; + Product__r.Unit_Text__c</formula>
        <inlineHelpText>Negotiated Price</inlineHelpText>
        <label>Price Per Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>SicProduct__c</referenceTo>
        <relationshipLabel>Negotiated Prices</relationshipLabel>
        <relationshipName>Negotiated_Prices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Negotiated Product</label>
    <nameField>
        <displayFormat>NP-{00000}</displayFormat>
        <label>Negotiated Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SicCategory__c.object
<CustomObject>
    <description>category of a product</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SicProduct__c.object
<CustomObject>
    <description>A Product in the Product Catalog
Note: don&apos;t make any field required, only set it required on page layouts
This will ensure that the customization works</description>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Product Category to assist users in browsing the catalog</inlineHelpText>
        <label>Category</label>
        <referenceTo>SicCategory__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>Item currency.
Must be maintained as ISO code in the SRM server.</description>
        <inlineHelpText>Item currency.
Must be maintained as ISO code in the SRM server.</inlineHelpText>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the item</description>
        <inlineHelpText>Description of the item</inlineHelpText>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <description>Detailed description of the product in Rich Text with images</description>
        <inlineHelpText>Detailed description of the product in Rich Text with images</inlineHelpText>
        <label>Detail</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lead_Time_Display__c</fullName>
        <description>Lead Time in text format</description>
        <formula>&apos;in &apos; +  TEXT(Lead_Time__c) + &apos; days&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Lead Time in text format</inlineHelpText>
        <label>Usually Ships</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <description>Delivery time of the item in days</description>
        <inlineHelpText>Delivery time of the item in days</inlineHelpText>
        <label>Lead Time</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <description>Long Description
Description of a configuration, for example.</description>
        <inlineHelpText>Long Description
Description of a configuration, for example.</inlineHelpText>
        <label>Long Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Product_Number__c</fullName>
        <description>Manufacturer Product Number
This information is sent via OCI</description>
        <inlineHelpText>Manufacturer Product Number</inlineHelpText>
        <label>Manufacturer Product Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PictureDocumentID__c</fullName>
        <description>ID of the Product Picture document object</description>
        <inlineHelpText>ID of the Product Picture document object</inlineHelpText>
        <label>Picture Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Display__c</fullName>
        <description>Price displayed as &apos;10 CAD per 1 EA&apos;</description>
        <formula>TEXT(Price__c) +  &apos; &apos; + TEXT(Currency__c) + IF(Unit_Text__c &lt;&gt; &apos;Each&apos;, &apos; per &apos;, &apos;&apos;) +   IF(Price_Unit__c &gt; 1, TEXT(Price_Unit__c), &apos;&apos;)   + &apos; &apos; +  Unit_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>price displayed with currency and price unit</inlineHelpText>
        <label>Price Per Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Unit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Price unit of the item</description>
        <inlineHelpText>Price unit of the item</inlineHelpText>
        <label>Price Unit</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of an item per price unit</description>
        <inlineHelpText>Price of an item per price unit</inlineHelpText>
        <label>Price</label>
        <precision>14</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNSPSC__c</fullName>
        <description>UNSPSC category expressed with the Commodity Ttitle</description>
        <inlineHelpText>UNSPSC category expressed with the Commodity Ttitle</inlineHelpText>
        <label>UNSPSC</label>
        <referenceTo>UNSPSC__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNSPSC_code__c</fullName>
        <description>UNSPSC Commodity Code, use this in OCI</description>
        <formula>UNSPSC__r.Commodity_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UNSPSC Commodity Code</inlineHelpText>
        <label>UNSPSC code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_ISO__c</fullName>
        <description>Unit ISO code</description>
        <formula>Unit__r.ISO__c</formula>
        <inlineHelpText>Unit ISO code, use this for OCI</inlineHelpText>
        <label>UnitISO</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Text__c</fullName>
        <description>Unit described with Text</description>
        <formula>Unit__r.Text__c</formula>
        <inlineHelpText>Unit</inlineHelpText>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UNSPSC__c.object
<CustomObject>
    <description>UNSPSC commodity codes</description>
    <label>UNSPSC</label>
    <nameField>
        <label>UNSPSC Commodity Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UNSPSC codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SicDao.cls
public with sharing class SicDao implements Dao{
    public Map<ID, OCIProduct> fetchAllToMap(ID buyerID) {
        Map<ID, OCIProduct> retval = new Map<ID, OCIProduct>();
        for(SicProduct__c p : [select
                                    id,
                                    name,
                                    Category__r.name,
                                    Description__c,
                                    Detail__c,
                                    Lead_Time__c,
                                    Lead_Time_Display__c,
                                    Long_Description__c,
                                    Manufacturer_Product_Number__c,
                                    PictureDocumentID__c,                           
                                    Price__c,
                                    Price_Display__c,                                   
                                    Price_Unit__c,
                                    Unit_Text__c,
                                    Currency__c,
                                    Unit_ISO__c,
                                    UNSPSC_code__c,
                                    UNSPSC__r.name,
                                     (Select id,
                                             Negotiated_Price__c,
                                             Price_Display__c 
                                      from Negotiated_Prices__r 
                                      where Buyer__c = :buyerID)
                                 from SicProduct__c]) {
            retval.put(p.ID, new SicOCIProduct(p));
        }
        return retval;
    }
    
    public OCIProduct fetchProductByID(ID productID, ID buyerID) {
        SicProduct__c p = [select
                                    id,
                                    name,
                                    Category__r.name,
                                    Description__c,
                                    Detail__c,
                                    Lead_Time__c,
                                    Lead_Time_Display__c,
                                    Long_Description__c,
                                    Manufacturer_Product_Number__c,
                                    PictureDocumentID__c,                           
                                    Price__c,
                                    Price_Display__c,                                   
                                    Price_Unit__c,
                                    Unit_Text__c,
                                    Currency__c,
                                    Unit_ISO__c,
                                    UNSPSC_code__c,
                                    UNSPSC__r.name,                                  
                                     (Select id,
                                             Negotiated_Price__c,
                                             Price_Display__c 
                                      from Negotiated_Prices__r 
                                      where Buyer__c = :buyerID)
                                 from SicProduct__c
                                 WHERE id = :productID
                                 ];
        return new SicOCIProduct(p);
    }
    
        //search function
    public Map<ID, OCIProduct> searchProductsByKeyword(String keyword, String categoryID, ID buyerID) {
        SicProduct__c[] products;
        if(keyword.trim().length() > 2) {        
            List<List<SObject>> searchresults;
            if(categoryID.trim().equals('all'))
                searchresults = [FIND :keyword RETURNING elisic__SicProduct__c (id)];
            else
                searchresults = [FIND :keyword RETURNING elisic__SicProduct__c (id WHERE Category__c = :categoryID)];
            products = [select
                                id,
                                name,
                                Category__r.name,
                                Description__c,
                                Detail__c,
                                Lead_Time__c,
                                Lead_Time_Display__c,
                                Long_Description__c,
                                Manufacturer_Product_Number__c,
                                PictureDocumentID__c,                           
                                Price__c,
                                Price_Display__c,                                   
                                Price_Unit__c,
                                Unit_Text__c,
                                Currency__c,
                                Unit_ISO__c,
                                UNSPSC_code__c,
                                UNSPSC__r.name,                                  
                                 (Select id,
                                         Negotiated_Price__c,
                                         Price_Display__c 
                                  from Negotiated_Prices__r 
                                  where Buyer__c = :buyerID)
                         from SicProduct__c
                         WHERE id IN : (elisic__SicProduct__c[])searchresults[0]];
        }
        else {
            if(categoryID.trim().equals('all'))
                products = [select
                                    id,
                                    name,
                                    Category__r.name,
                                    Description__c,
                                    Detail__c,
                                    Lead_Time__c,
                                    Lead_Time_Display__c,
                                    Long_Description__c,
                                    Manufacturer_Product_Number__c,
                                    PictureDocumentID__c,                           
                                    Price__c,
                                    Price_Display__c,                                   
                                    Price_Unit__c,
                                    Unit_Text__c,
                                    Currency__c,
                                    Unit_ISO__c,
                                    UNSPSC_code__c,
                                    UNSPSC__r.name,                                  
                                     (Select id,
                                             Negotiated_Price__c,
                                             Price_Display__c 
                                      from Negotiated_Prices__r 
                                      where Buyer__c = :buyerID)
                             from SicProduct__c];
            else
                products = [select
                                    id,
                                    name,
                                    Category__r.name,
                                    Description__c,
                                    Detail__c,
                                    Lead_Time__c,
                                    Lead_Time_Display__c,
                                    Long_Description__c,
                                    Manufacturer_Product_Number__c,
                                    PictureDocumentID__c,                           
                                    Price__c,
                                    Price_Display__c,                                   
                                    Price_Unit__c,
                                    Unit_Text__c,
                                    Currency__c,
                                    Unit_ISO__c,
                                    UNSPSC_code__c,
                                    UNSPSC__r.name,                                  
                                     (Select id,
                                             Negotiated_Price__c,
                                             Price_Display__c 
                                      from Negotiated_Prices__r 
                                      where Buyer__c = :buyerID)
                             from SicProduct__c
                             WHERE Category__c = :categoryID];
        }
        Map<ID, OCIProduct> retval = new Map<ID, OCIProduct>();
        for(SicProduct__c p : products) {
            retval.put(p.ID, new SicOCIProduct(p));
        }
        return retval;             
    }
 
}