src/objects/Buyer__c.object
<CustomObject>
    <description>Buyer is an organisation that is able to access the catalog.
It is possible to set up a list of products with negotiated prices for each Buyer
Buyers authenticate by sending username/password via OCI</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>sent in ``password&apos;&apos; parameter via OCI when accessing the OCI_Entry page</description>
        <inlineHelpText>Sent in ``password&apos;&apos; parameter via OCI when accessing the OCI_Entry page
This has to be configured in the Buyer&apos;s SAP system.</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>sent in ``username&apos;&apos; parameter via OCI when accessing the OCI_Entry page</description>
        <inlineHelpText>Sent in ``username&apos;&apos; parameter via OCI when accessing the OCI_Entry page
This has to be configured in the Buyer&apos;s SAP system</inlineHelpText>
        <label>User Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Buyer</label>
    <nameField>
        <label>Buyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negotiated_Product__c.object
<CustomObject>
    <description>Products that a Buyer has approved from the entire product list.
Products have a negotiated price.</description>
    <fields>
        <fullName>Buyer__c</fullName>
        <label>Buyer</label>
        <referenceTo>Buyer__c</referenceTo>
        <relationshipLabel>Negotiated Products</relationshipLabel>
        <relationshipName>Negotiated_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Negotiated_Price__c</fullName>
        <label>Negotiated Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>SicProduct__c</referenceTo>
        <relationshipLabel>Negotiated Prices</relationshipLabel>
        <relationshipName>Negotiated_Prices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Negotiated Product</label>
    <nameField>
        <displayFormat>NP-{00000}</displayFormat>
        <label>Negotiated Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SicCategory__c.object
<CustomObject>
    <description>category of a product</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SicProduct__c.object
<CustomObject>
    <description>A Product in the Product Catalog
Note: don&apos;t make any field required, only set it required on page layouts
This will ensure that the customization works</description>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Product Category to assist users in browsing the catalog</inlineHelpText>
        <label>Category</label>
        <referenceTo>SicCategory__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>Item currency.
Must be maintained as ISO code in the SRM server.</description>
        <inlineHelpText>Item currency.
Must be maintained as ISO code in the SRM server.</inlineHelpText>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the item</description>
        <inlineHelpText>Description of the item</inlineHelpText>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <description>Detailed description of the product in Rich Text with images</description>
        <inlineHelpText>Detailed description of the product in Rich Text with images</inlineHelpText>
        <label>Detail</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <description>Delivery time of the item in days</description>
        <inlineHelpText>Delivery time of the item in days</inlineHelpText>
        <label>Lead Time</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <description>Long Description
Description of a configuration, for example.</description>
        <inlineHelpText>Long Description
Description of a configuration, for example.</inlineHelpText>
        <label>Long Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Product_Number__c</fullName>
        <description>Manufacturer Product Number
This information is sent via OCI</description>
        <inlineHelpText>Manufacturer Product Number</inlineHelpText>
        <label>Manufacturer Product Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PictureDocumentID__c</fullName>
        <description>ID of the Product Picture document object</description>
        <inlineHelpText>ID of the Product Picture document object</inlineHelpText>
        <label>Picture Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Unit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Price unit of the item</description>
        <inlineHelpText>Price unit of the item</inlineHelpText>
        <label>Price Unit</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of an item per price unit</description>
        <inlineHelpText>Price of an item per price unit</inlineHelpText>
        <label>Price</label>
        <precision>14</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNSPSC__c</fullName>
        <description>UNSPSC category expressed with the Commodity Ttitle</description>
        <inlineHelpText>UNSPSC category expressed with the Commodity Ttitle</inlineHelpText>
        <label>UNSPSC</label>
        <referenceTo>UNSPSC__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>measurement unit</description>
        <inlineHelpText>measurement unit</inlineHelpText>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>measurement units with ISO codes</description>
    <fields>
        <fullName>ISO__c</fullName>
        <description>ISO code of unit</description>
        <label>ISO</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>human readable text of unit</description>
        <inlineHelpText>human readable text of unit</inlineHelpText>
        <label>Text</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UNSPSC__c.object
<CustomObject>
    <description>UNSPSC commodity codes</description>
    <fields>
        <fullName>Commodity_Code__c</fullName>
        <description>UNSPSC Commodity Code</description>
        <inlineHelpText>UNSPSC Commodity Code</inlineHelpText>
        <label>Commodity Code</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UNSPSC</label>
    <nameField>
        <label>UNSPSC Commodity Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UNSPSC codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UTSicDao.cls
@isTest
private class UTSicDao {

    static testmethod void testFetchAll() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	Map<ID, OCIProduct> products = dao.fetchAllToMap(null);
    	// System.assertEquals(3, products.size());
    	System.assertEquals(products.get(ids[0]).getID() , ids[0]);
    	System.assertEquals(products.get(ids[1]).getID() , ids[1]);
    	System.assertEquals(products.get(ids[2]).getID() , ids[2]);
    	System.assertEquals(products.get(ids[3]).getID() , ids[3]);
    }
    static testmethod void testFetchbyID() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	OCIProduct p = dao.fetchProductByID(ids[0], null);
    	System.assertEquals(p.getName(), 'desc1');
    }
    
    public static ID[] setupSearchTestData() {
		SicCategory__c c1 = new SicCategory__c(Name = 'cat1');
		insert c1; 
		SicCategory__c c2 = new SicCategory__c(Name = 'cat2');
		insert c2; 
		UNSPSC__c unspsc = new UNSPSC__c();
		unspsc.Name = 'unspsc1';
		unspsc.Commodity_Code__c = 'commoditycode1';
		insert unspsc;
		Unit__c unit = new Unit__c();
		unit.ISO__c = 'iso';
		unit.Name = 'unit1';
		unit.Text__c = 'unittext1';
		insert unit;
		Buyer__c buyer = new Buyer__c();
		buyer.name = 'city';
		buyer.User_Name__c = 'username';
		buyer.Password__c = 'password';
		insert buyer;

		// product w/ category w/ buyer
		SicProduct__c sp_cat_buyer = new SicProduct__c(
			Category__c = c1.id,
			Currency__c = 'CAD',
			Description__c = 'desc1',
			Detail__c = 'detail1',
			Lead_Time__c = 2,
			Long_Description__c = 'longdesc1',
			Manufacturer_Product_Number__c = 'mpn1',
			PictureDocumentID__c = 'pdid',
			Price_Unit__c = 100,
			Price__c = 5,
			UNSPSC__c = unspsc.id,
			Unit__c = unit.id
		);
		insert sp_cat_buyer;
		Negotiated_Product__c np1 = new Negotiated_Product__c();
		np1.Buyer__c = buyer.id;
		np1.Product__c = sp_cat_buyer.Id;
		np1.Negotiated_Price__c = 4;
		insert np1;

		// product w/ category no buyer
		SicProduct__c sp_cat_nobuyer = new SicProduct__c(
			Category__c = c1.id,
			Currency__c = 'CAD',
			Description__c = 'desc2',
			Detail__c = 'detail2',
			Lead_Time__c = 2,
			Long_Description__c = 'longdesc2',
			Manufacturer_Product_Number__c = 'mpn2',
			PictureDocumentID__c = 'pdid',
			Price_Unit__c = 100,
			Price__c = 5,
			UNSPSC__c = unspsc.id,
			Unit__c = unit.id
		);
		insert sp_cat_nobuyer;
		
		// product no category w/ buyer
		SicProduct__c sp_nocat_buyer = new SicProduct__c(
			Category__c = c2.id,
			Currency__c = 'CAD',
			Description__c = 'desc3',
			Detail__c = 'detail3',
			Lead_Time__c = 2,
			Long_Description__c = 'longdesc3',
			Manufacturer_Product_Number__c = 'mpn3',
			PictureDocumentID__c = 'pdid',
			Price_Unit__c = 100,
			Price__c = 5,
			UNSPSC__c = unspsc.id,
			Unit__c = unit.id
		);
		insert sp_nocat_buyer;
		Negotiated_Product__c np2 = new Negotiated_Product__c();
		np2.Buyer__c = buyer.id;
		np2.Product__c = sp_nocat_buyer.id;
		np2.Negotiated_Price__c = 4;
		insert np2;
		
		// product no category no buyer
		SicProduct__c sp_nocat_nobuyer = new SicProduct__c(
			Category__c = c2.id,
			Currency__c = 'CAD',
			Description__c = 'desc4',
			Detail__c = 'detail4',
			Lead_Time__c = 2,
			Long_Description__c = 'longdesc4',
			Manufacturer_Product_Number__c = 'mpn4',
			PictureDocumentID__c = 'pdid',
			Price_Unit__c = 100,
			Price__c = 5,
			UNSPSC__c = unspsc.id,
			Unit__c = unit.id
		);
		insert sp_nocat_nobuyer;
		
		//return IDs in order
		ID[] retval = new ID[4];
		retval[0] = sp_cat_buyer.id;
		retval[1] = sp_cat_nobuyer.id;
		retval[2] = sp_nocat_buyer.id;
		retval[3] = sp_nocat_nobuyer.id;
		
		// set up search results
		Test.setFixedSearchResults(retval);
		
		return retval;
   }
    
    static testmethod void testSearchNoKeywordAllNoBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('', 'all', null);
    	System.assert(products.containsKey(ids[0]));
    	System.assert(products.containsKey(ids[1]));
    	System.assert(products.containsKey(ids[2]));
    	System.assert(products.containsKey(ids[3]));    	
    }
    static testmethod void testSearchNoKeywordAllBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	Buyer__c buyer = [select id from Buyer__c where name = 'city'];
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('', 'all', buyer.id);
    	System.assert(products.containsKey(ids[0]));
    	System.assert(products.containsKey(ids[2]));
    }
    static testmethod void testSearchNoKeywordCategoryNoBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	SicCategory__c category = [select id from SicCategory__c where name = 'cat1'];
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('', category.id, null);
    	System.assert(products.containsKey(ids[0]));
    	System.assert(products.containsKey(ids[1]));
    }
    static testmethod void testSearchNoKeywordCategoryBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	Buyer__c buyer = [select id from Buyer__c where name = 'city'];
    	SicCategory__c category = [select id from SicCategory__c where name = 'cat1'];
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('', category.id, buyer.id);
    	System.assert(products.containsKey(ids[0]));
    }
    static testmethod void testSearchKeywordAllNoBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('dummy', 'all', null);
    	System.assertEquals(products.size(), 4);
    }
    static testmethod void testSearchKeywordAllBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	Buyer__c buyer = [select id from Buyer__c where name = 'city'];
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('dummy', 'all', buyer.id);
    	System.assertEquals(products.size(), 4);
    }
    static testmethod void testSearchKeywordCategoryNoBuyer() {
    	ID[] ids = setupSearchTestData();
    	SicDao dao = new SicDao();
    	SicCategory__c category = [select id from SicCategory__c where name = 'cat1'];
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('dummy', category.id, null);
    	System.assertEquals(products.size(), 2);
    	System.assert(products.containsKey(ids[0]));
    	System.assert(products.containsKey(ids[1]));
    	
    }
    static testmethod void testSearchKeywordCategoryBuyer() {
    	ID[] ids =  setupSearchTestData();
    	SicDao dao = new SicDao();
    	SicCategory__c category = [select id from SicCategory__c where name = 'cat1'];
    	Buyer__c buyer = [select id from Buyer__c where name = 'city'];
    	Map<ID, OCIProduct> products = dao.searchProductsByKeyword('dummy', category.id, buyer.id);
    	System.assertEquals(products.size(), 2);
    	System.assert(products.containsKey(ids[0]));
    	System.assert(products.containsKey(ids[1]));
    }
}