src/objects/Buyer__c.object
<CustomObject>
    <description>Buyer is an organisation that is able to access the catalog.
It is possible to set up a list of products with negotiated prices for each Buyer
Buyers authenticate by sending username/password via OCI</description>
    <fields>
        <fullName>Password__c</fullName>
        <description>sent in ``password&apos;&apos; parameter via OCI when accessing the OCI_Entry page</description>
        <inlineHelpText>Sent in ``password&apos;&apos; parameter via OCI when accessing the OCI_Entry page
This has to be configured in the Buyer&apos;s SAP system.</inlineHelpText>
        <label>Password</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Name__c</fullName>
        <description>sent in ``username&apos;&apos; parameter via OCI when accessing the OCI_Entry page</description>
        <inlineHelpText>Sent in ``username&apos;&apos; parameter via OCI when accessing the OCI_Entry page
This has to be configured in the Buyer&apos;s SAP system</inlineHelpText>
        <label>User Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Buyer</label>
    <nameField>
        <label>Buyer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Buyers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Negotiated_Product__c.object
<CustomObject>
    <description>Products that a Buyer has approved from the entire product list.
Products have a negotiated price.</description>
    <fields>
        <fullName>Buyer__c</fullName>
        <label>Buyer</label>
        <referenceTo>Buyer__c</referenceTo>
        <relationshipLabel>Negotiated Products</relationshipLabel>
        <relationshipName>Negotiated_Products</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Negotiated_Price__c</fullName>
        <label>Negotiated Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Display__c</fullName>
        <formula>TEXT(Negotiated_Price__c) + &apos; &apos; + TEXT(Product__r.Currency__c) + IF(Product__r.Unit_Text__c &lt;&gt; &apos;Each&apos;, &apos; per &apos;, &apos;&apos;) + IF(Product__r.Price_Unit__c &gt; 1, TEXT(Product__r.Price_Unit__c), &apos;&apos;) + &apos; &apos; + Product__r.Unit_Text__c</formula>
        <inlineHelpText>Negotiated Price</inlineHelpText>
        <label>Price Per Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <label>Product</label>
        <referenceTo>SicProduct__c</referenceTo>
        <relationshipLabel>Negotiated Prices</relationshipLabel>
        <relationshipName>Negotiated_Prices</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Negotiated Product</label>
    <nameField>
        <displayFormat>NP-{00000}</displayFormat>
        <label>Negotiated Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Negotiated Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/SicCategory__c.object
<CustomObject>
    <description>category of a product</description>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SicProduct__c.object
<CustomObject>
    <description>A Product in the Product Catalog
Note: don&apos;t make any field required, only set it required on page layouts
This will ensure that the customization works</description>
    <fields>
        <fullName>Category__c</fullName>
        <inlineHelpText>Product Category to assist users in browsing the catalog</inlineHelpText>
        <label>Category</label>
        <referenceTo>SicCategory__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <description>Item currency.
Must be maintained as ISO code in the SRM server.</description>
        <inlineHelpText>Item currency.
Must be maintained as ISO code in the SRM server.</inlineHelpText>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>CAD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EUR</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the item</description>
        <inlineHelpText>Description of the item</inlineHelpText>
        <label>Description</label>
        <length>40</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Detail__c</fullName>
        <description>Detailed description of the product in Rich Text with images</description>
        <inlineHelpText>Detailed description of the product in Rich Text with images</inlineHelpText>
        <label>Detail</label>
        <length>32000</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lead_Time_Display__c</fullName>
        <description>Lead Time in text format</description>
        <formula>&apos;in &apos; +  TEXT(Lead_Time__c) + &apos; days&apos;</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Lead Time in text format</inlineHelpText>
        <label>Usually Ships</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Time__c</fullName>
        <description>Delivery time of the item in days</description>
        <inlineHelpText>Delivery time of the item in days</inlineHelpText>
        <label>Lead Time</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Long_Description__c</fullName>
        <description>Long Description
Description of a configuration, for example.</description>
        <inlineHelpText>Long Description
Description of a configuration, for example.</inlineHelpText>
        <label>Long Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Manufacturer_Product_Number__c</fullName>
        <description>Manufacturer Product Number
This information is sent via OCI</description>
        <inlineHelpText>Manufacturer Product Number</inlineHelpText>
        <label>Manufacturer Product Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PictureDocumentID__c</fullName>
        <description>ID of the Product Picture document object</description>
        <inlineHelpText>ID of the Product Picture document object</inlineHelpText>
        <label>Picture Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Display__c</fullName>
        <description>Price displayed as &apos;10 CAD per 1 EA&apos;</description>
        <formula>TEXT(Price__c) +  &apos; &apos; + TEXT(Currency__c) + IF(Unit_Text__c &lt;&gt; &apos;Each&apos;, &apos; per &apos;, &apos;&apos;) +   IF(Price_Unit__c &gt; 1, TEXT(Price_Unit__c), &apos;&apos;)   + &apos; &apos; +  Unit_Text__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>price displayed with currency and price unit</inlineHelpText>
        <label>Price Per Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Price_Unit__c</fullName>
        <defaultValue>1</defaultValue>
        <description>Price unit of the item</description>
        <inlineHelpText>Price unit of the item</inlineHelpText>
        <label>Price Unit</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of an item per price unit</description>
        <inlineHelpText>Price of an item per price unit</inlineHelpText>
        <label>Price</label>
        <precision>14</precision>
        <scale>3</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UNSPSC__c</fullName>
        <description>UNSPSC category expressed with the Commodity Ttitle</description>
        <inlineHelpText>UNSPSC category expressed with the Commodity Ttitle</inlineHelpText>
        <label>UNSPSC</label>
        <referenceTo>UNSPSC__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UNSPSC_code__c</fullName>
        <description>UNSPSC Commodity Code, use this in OCI</description>
        <formula>UNSPSC__r.Commodity_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>UNSPSC Commodity Code</inlineHelpText>
        <label>UNSPSC code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_ISO__c</fullName>
        <description>Unit ISO code</description>
        <formula>Unit__r.ISO__c</formula>
        <inlineHelpText>Unit ISO code, use this for OCI</inlineHelpText>
        <label>UnitISO</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Text__c</fullName>
        <description>Unit described with Text</description>
        <formula>Unit__r.Text__c</formula>
        <inlineHelpText>Unit</inlineHelpText>
        <label>Unit</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <description>measurement unit</description>
        <inlineHelpText>measurement unit</inlineHelpText>
        <label>Unit</label>
        <referenceTo>Unit__c</referenceTo>
        <relationshipLabel>Products</relationshipLabel>
        <relationshipName>Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <description>measurement units with ISO codes</description>
    <fields>
        <fullName>ISO__c</fullName>
        <description>ISO code of unit</description>
        <label>ISO</label>
        <length>3</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Text__c</fullName>
        <description>human readable text of unit</description>
        <inlineHelpText>human readable text of unit</inlineHelpText>
        <label>Text</label>
        <length>30</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <label>Unit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/UNSPSC__c.object
<CustomObject>
    <description>UNSPSC commodity codes</description>
    <fields>
        <fullName>Commodity_Code__c</fullName>
        <description>UNSPSC Commodity Code</description>
        <inlineHelpText>UNSPSC Commodity Code</inlineHelpText>
        <label>Commodity Code</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>UNSPSC</label>
    <nameField>
        <label>UNSPSC Commodity Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UNSPSC codes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SicOCIProduct.cls
public class SicOCIProduct implements OCIProduct {
    private SicProduct__c p;
    private Decimal qty; // calling it `quantity' causes naming conflict with get/setQuantity methods!
    public SicOCIProduct(SicProduct__c p) {
        this.p = p;
        this.qty = p.Price_Unit__c;
        this.qty.setScale(3, System.Roundingmode.HALF_UP);
    }
    private SicOCIProduct() {
        this.p = new SicProduct__c();
        this.qty = 0;
    }
     public ID getID() {
        return p.ID;
     }
     public String getCode() { //name
        return p.Name;
     }
     public String getCategory() {
        return p.Category__r.name;
     }
     public String getName() { //description
        return p.Description__c;
     }
     public String getDetail() {
        return p.Detail__c;
     }
     public Integer getLeadTime() {
        return p.Lead_Time__c.intValue();
     }
     public String getLeadTimeDisplay() {
        return p.Lead_Time_Display__c;
     }
     public String getDescription() { // long description
        return p.Long_Description__c;
     }
     public String getManufacturerProductNumber() {
        return p.Manufacturer_Product_Number__c;
     }
     public String getPictureDocumentID() {
        return p.PictureDocumentID__c;
     }
     public Decimal getOriginal_price() {
        return p.Price__c;
     }
     public String getOriginal_priceDisplay() {
        return p.Price_Display__c;
     }
     public Decimal getNegotiated_price() {
        if(p.Negotiated_Prices__r.size() > 0) {
            return p.Negotiated_Prices__r[0].Negotiated_Price__c;
        }
        else {
            return null;
        }
     }
     public String getNegotiated_priceDisplay() {
        if(p.Negotiated_Prices__r.size() > 0) {
            return p.Negotiated_Prices__r[0].Price_Display__c;
        }
        else {
            return '';
        }       
     }
     public Decimal getPrice() {
        if(p.Negotiated_Prices__r.size() > 0) {
            return p.Negotiated_Prices__r[0].Negotiated_Price__c;
        }
        else {
            return p.Price__c;
        }               
     }
     public String getPriceDisplay() {
        if(p.Negotiated_Prices__r.size() > 0) {
            return p.Negotiated_Prices__r[0].Price_Display__c;
        }
        else {
            return p.Price_Display__c;
        }                       
     }
     public Integer getPriceUnit() {
        return p.Price_Unit__c.intValue();
     }
     public String getCurrencyDisplay() {
        return p.Currency__c;
     }
     public String getUnitDisplay() {
        return p.Unit_Text__c;
     }
     public String getUnitISO() {
        return p.Unit_ISO__c;
     }
     public String getUNSPSCcode() {
        return p.UNSPSC_code__c;
     }
     public String getUNSPSC() {
        return p.UNSPSC__r.name;
     }
     // calculated
     public boolean getApproved() {
        return p.Negotiated_Prices__r.size()>0;
     }
     public String getQuantity() {
        return this.qty.toPlainString();
     }
     public void setQuantity(String value) {
         try {
            this.qty = decimal.valueOf(value);
         }
         catch (Exception e) {
             ApexPages.addMessages(e);
         }           
     }
     public Long getCost() {
        Decimal d_cost = this.qty * getPrice() / getPriceUnit();
        return d_cost.longValue();
     }
     public Long getSaving() {
        Decimal d_saving = this.qty * getOriginal_Price() / getPriceUnit() - getCost();
        return d_saving.longValue();
     }

	// TEST
	static testmethod void testCtor() {
		SicCategory__c c = new SicCategory__c(Name = 'cat1');
		insert c; 
		UNSPSC__c unspsc = new UNSPSC__c();
		unspsc.Name = 'unspsc1';
		unspsc.Commodity_Code__c = 'commoditycode1';
		insert unspsc;
		Unit__c unit = new Unit__c();
		unit.ISO__c = 'iso';
		unit.Name = 'unit1';
		unit.Text__c = 'unittext1';
		insert unit;
		Buyer__c buyer = new Buyer__c();
		buyer.name = 'city';
		buyer.User_Name__c = 'username';
		buyer.Password__c = 'password';
		insert buyer;
		SicProduct__c sp = new SicProduct__c(
			Category__c = c.id,
			Currency__c = 'CAD',
			Description__c = 'desc1',
			Detail__c = 'detail1',
			Lead_Time__c = 2,
			Long_Description__c = 'longdesc1',
			Manufacturer_Product_Number__c = 'mpn1',
			PictureDocumentID__c = 'pdid',
			Price_Unit__c = 100,
			Price__c = 5,
			UNSPSC__c = unspsc.id,
			Unit__c = unit.id
		);
		insert sp;

		Negotiated_Product__c np = new Negotiated_Product__c();
		np.Buyer__c = buyer.id;
		np.Product__c = sp.id;
		np.Negotiated_Price__c = 4;
		insert np;
		
		SicProduct__c sp2 = [select id, name from SicProduct__c where id = :sp.id];

		Dao dao = DaoFactory.getDao();		
		OCIProduct p = dao.fetchProductByID(sp.id, null); //no buyer
		
	    System.assertEquals(p.getID(), sp.Id);
	    System.assertEquals(p.getCode(), sp2.Name);
	    System.assertEquals(p.getCategory(), 'cat1');
	    System.assertEquals(p.getName(), 'desc1');
	    System.assertEquals(p.getDetail(), 'detail1');
	    System.assertEquals(p.getLeadTime(), 2);
	    System.assertEquals(p.getLeadTimeDisplay(), 'in 2 days');
	    System.assertEquals(p.getDescription(), 'longdesc1');
	    System.assertEquals(p.getManufacturerProductNumber(), 'mpn1');
	    System.assertEquals(p.getPictureDocumentID(), 'pdid');
	    System.assertEquals(p.getOriginal_price(), 5);
	    System.assertEquals(p.getOriginal_priceDisplay(), '5 CAD per 100 unittext1');
	    System.assertEquals(p.getNegotiated_price(), null);
	    System.assertEquals(p.getNegotiated_priceDisplay(), '');
	    System.assertEquals(p.getPrice(), 5);
	    System.assertEquals(p.getPriceDisplay(), '5 CAD per 100 unittext1');
	    System.assertEquals(p.getPriceUnit(), 100);
	    System.assertEquals(p.getCurrencyDisplay(), 'CAD');
	    System.assertEquals(p.getUnitDisplay(), 'unittext1');
	    System.assertEquals(p.getUnitISO(), 'iso');
	    System.assertEquals(p.getUNSPSCcode(), 'commoditycode1');
	    System.assertEquals(p.getUNSPSC(), 'unspsc1'); 
	    System.assertEquals(p.getApproved(), false);
	    
		p.setQuantity('700');	    
	    
	    System.assertEquals(p.getQuantity(), '700');
	    System.assertEquals(p.getCost(), 35);
	    System.assertEquals(p.getSaving(), 0);
	    
	    p = dao.fetchProductByID(sp.id, buyer.id); //buyer
	    
	    System.assertEquals(p.getOriginal_price(), 5);
	    System.assertEquals(p.getOriginal_priceDisplay(), '5 CAD per 100 unittext1');
	    System.assertEquals(p.getNegotiated_price(), 4);
	    System.assertEquals(p.getNegotiated_priceDisplay(), '4 CAD per 100 unittext1');
	    System.assertEquals(p.getPrice(), 4);
	    System.assertEquals(p.getPriceDisplay(), '4 CAD per 100 unittext1');
	    System.assertEquals(p.getPriceUnit(), 100);
	    System.assertEquals(p.getCurrencyDisplay(), 'CAD');
	    System.assertEquals(p.getApproved(), true);
	    
		p.setQuantity('700');	    
	    
	    System.assertEquals(p.getQuantity(), '700');
	    System.assertEquals(p.getCost(), 28);
	    System.assertEquals(p.getSaving(), 7);
	}
	
}