src/objects/SicProduct__c.object
<CustomObject>
    <description>A Product in the Product Catalog
Note: don&apos;t make any field required, only set it required on page layouts
This will ensure that the customization works</description>
    <fields>
        <fullName>PictureDocumentID__c</fullName>
        <description>ID of the Product Picture document object</description>
        <inlineHelpText>ID of the Product Picture document object</inlineHelpText>
        <label>Picture Document ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Product</label>
    <nameField>
        <displayFormat>P-{0000}</displayFormat>
        <label>Product Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ceUploadPictureDocument.cls
public class ceUploadPictureDocument {

    public Document PictureDocument {get; set;}
    private SicProduct__c product;
    public ceUploadPictureDocument(ApexPages.StandardController controller) {
        this.product = (SicProduct__c)controller.getRecord();
        PictureDocument = new Document();
    }

    public PageReference doUploadPicture() {
        Folder folder = [select id from Folder where DeveloperName = 'SicProduct_Pictures'];
        PictureDocument.FolderID = folder.id;
        PictureDocument.IsPublic = true;
        insert Picturedocument;
        product.PictureDocumentID__c = PictureDocument.ID;
        update product;
        PageReference thePage = new PageReference( '/'+ product.id);
        thePage.setRedirect( true );        
        return thePage;        
    }
    

}